const TemuTerms = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-2xl shadow-sm p-8 sm:p-12">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Temu Advertiser Terms & Conditions</h1>
          <p className="text-gray-500 text-sm mb-8">Effective: January 2026 (CPS Program)</p>

          {/* Program Overview */}
          <div className="mb-10 p-6 bg-blue-50 rounded-xl border border-blue-100">
            <h2 className="text-lg font-semibold text-blue-900 mb-4">Program Overview</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm text-blue-800">
              <div>
                <p className="font-medium">Action Type</p>
                <p className="text-blue-700">Website Purchase</p>
              </div>
              <div>
                <p className="font-medium">Referral Period</p>
                <p className="text-blue-700">1 day(s)</p>
              </div>
              <div>
                <p className="font-medium">Occurrences</p>
                <p className="text-blue-700">Unlimited</p>
              </div>
              <div>
                <p className="font-medium">Locking Method</p>
                <p className="text-blue-700">Custom (90 days)</p>
              </div>
              <div>
                <p className="font-medium">Base Commission</p>
                <p className="text-blue-700">0.00%</p>
              </div>
            </div>

            <div className="mt-5">
              <p className="font-medium text-blue-900 mb-2">Commission by Customer Type</p>
              <div className="overflow-x-auto">
                <table className="w-full text-sm text-blue-800 border-collapse">
                  <thead>
                    <tr className="bg-blue-100">
                      <th className="text-left px-3 py-2 rounded-tl font-medium">Segment</th>
                      <th className="text-left px-3 py-2 font-medium">Platform</th>
                      <th className="text-left px-3 py-2 rounded-tr font-medium">Commission</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-blue-100">
                    <tr>
                      <td className="px-3 py-2">New Customer</td>
                      <td className="px-3 py-2">Web</td>
                      <td className="px-3 py-2 font-semibold text-green-700">10.00%</td>
                    </tr>
                    <tr>
                      <td className="px-3 py-2">Returning Customer</td>
                      <td className="px-3 py-2">Web</td>
                      <td className="px-3 py-2">0.00%</td>
                    </tr>
                    <tr>
                      <td className="px-3 py-2">New Customer</td>
                      <td className="px-3 py-2">App</td>
                      <td className="px-3 py-2 font-semibold text-green-700">10.00%</td>
                    </tr>
                    <tr>
                      <td className="px-3 py-2">Returning Customer</td>
                      <td className="px-3 py-2">App</td>
                      <td className="px-3 py-2">0.00%</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <p className="mt-2 text-xs text-blue-600">Cashback is only available for new Temu customers. No cashback is earned on orders placed by returning customers.</p>
            </div>
          </div>

          <div className="prose prose-gray max-w-none space-y-8 text-gray-700">

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Introduction</h2>
              <p>These Terms and Conditions (these "Terms"), including all exhibits and attachments (collectively the "Agreement") hereto and incorporated herein by reference, are entered into by Whaleco Inc. and its parent, affiliate, subsidiary and related entities ("Advertiser") and you, the "Media Partner" to utilize the platform at www.cj.com (the "Platform") owned and operated by Commission Junction LLC ("CJ").</p>
              <p className="mt-3">In the event of any conflict or inconsistency between any term below and the Publisher Service Agreement ("PSA") between the Media Partner and CJ, the PSA shall control. A Qualifying Link refers to a unique link/code generated by the Advertiser for the Media Partner that directs users to Advertiser's website or mobile app ("Site"). All such tracking links shall be the tracking links provided through the Platform for the respective advertising placements.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Restrictions</h2>
              <p>Media Partner may not violate any law, infringe or violate the rights of any third party, or otherwise act in a manner that is deemed harassing, harmful, illegal, hateful, obscene or outside the spirit and intent of these Terms. Media Partner may not act in an unfair or disruptive manner, or use any system, bot or other device or artifice to fulfill these Terms or receive any benefit.</p>
              <p className="mt-3 font-semibold uppercase text-sm">CAUTION: ANY ATTEMPT TO DELIBERATELY DAMAGE OR UNDERMINE THE LEGITIMATE OPERATION OF THESE TERMS MAY BE IN VIOLATION OF CRIMINAL AND CIVIL LAWS. ADVERTISER RESERVES THE RIGHT TO SEEK REMEDIES AND DAMAGES (INCLUDING ATTORNEY FEES) TO THE FULLEST EXTENT OF THE LAW, INCLUDING CRIMINAL PROSECUTION.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Taxes</h2>
              <p>All taxes applicable to any benefits provided under this Agreement will be Media Partner's responsibility and all Payouts are exclusive of VAT, sales tax, digital service tax or other indirect taxes. Media Partner is solely responsible for any and all tax liability resulting from receipt of fees. Advertiser shall not pay any amounts for Media Partners' income tax, withholding tax, social security, unemployment or worker's compensation.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Representations and Warranties; Indemnification</h2>
              <p>Media Partner represents, warrants, and covenants that:</p>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li>Media Partner will create, maintain, and operate the Affiliate Site in accordance with these Terms.</li>
                <li>Media Partner's participation will not violate any applicable laws, ordinances, rules, regulations, or requirements of any governmental authority.</li>
                <li>Media Partner is lawfully able to enter into contracts.</li>
                <li>Media Partner has independently evaluated the desirability of participating in the Program.</li>
                <li>Media Partner will not use any Service Offerings if subject to applicable sanctions.</li>
                <li>Media Partner will comply with all export and re-export restrictions consistent with applicable law.</li>
                <li>The information Media Partner provides is accurate and complete at all times.</li>
                <li>Media Partner shall not knowingly engage in advertising activities directed at individuals considered children under the applicable Temu Privacy Policy.</li>
              </ul>
              <p className="mt-3">Media Partner agrees to indemnify, defend and hold Advertiser and its representatives harmless from and against any third-party claims, demands, liabilities, costs or expenses arising from, or related to any breach of these Terms.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Limitation of Liability</h2>
              <p>To the fullest extent permitted by applicable law, no responsibility or liability is assumed by Advertiser for technical problems or technical malfunction arising in connection with hardware or software errors, faulty computer or network issues, Internet connectivity problems, garbled data transmissions, unauthorized tampering, hacking, theft, virus, bugs, or worms.</p>
              <p className="mt-3">To the fullest extent permitted by applicable law: (i) any and all disputes shall be resolved individually, without resorting to class action; (ii) any and all claims shall be limited to actual out-of-pocket costs incurred; and (iii) punitive, incidental and consequential damages are waived.</p>
              <p className="mt-3 font-semibold text-sm">EVERYTHING PROVIDED IN RELATION TO THESE TERMS IS PROVIDED "AS IS" WITHOUT ANY WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Privacy</h2>
              <p>Advertiser may make available certain information relating to Advertiser's Site or users ("User Data"). User Data is Advertiser's Confidential Information. Media Partner may not use User Data other than for the purpose for which it was provided, and under no circumstances to create or augment audience profiles.</p>
              <p className="mt-3">Media Partner must maintain and post a privacy notice on Media Partner's websites or applications that complies with all applicable laws. Media Partner is responsible for all personally identifiable information collected from end users and must obtain valid consent as required by applicable law.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Intellectual Property</h2>
              <p>Unless explicitly authorized, Media Partner shall not promote Advertiser materials using:</p>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li>Provision of leads obtained other than through intended consumer action.</li>
                <li>Use of fake redirects, automated software, or other mechanisms to generate Actions.</li>
                <li>Actions that are not in good faith, such as those using automated devices, robots, or hidden frames.</li>
                <li>Use of incentives to procure Actions from End Users.</li>
              </ul>
              <p className="mt-3">Media Partner acknowledges no proprietary rights in Advertiser's trademarks, trade names, URLs, copyrighted material, or other intellectual property. When using the Temu name/trademark:</p>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li>Use "Temu" only in a descriptive manner.</li>
                <li>Capitalize as "Temu" or "TEMU" only.</li>
                <li>Do not combine a generic or descriptive name with "TEMU" as a prefix or suffix.</li>
                <li>Do not use Temu as a verb.</li>
                <li>Do not modify any logo provided by Advertiser.</li>
                <li>Multiple colors invoking Advertiser's logo is prohibited.</li>
                <li>Do not use Advertiser's logo within a sentence.</li>
                <li>Do not use Advertiser's name/trademarks in offline material or email.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Prohibitions</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>Do not use link shortening services in a manner that makes it unclear that Media Partner is linking to Advertiser's Site.</li>
                <li>Do not include any Qualifying Link in any content placed on Advertiser's Site.</li>
                <li>Do not modify, redirect, suppress, or substitute the operation of any button, link, or other feature of Advertiser's Site.</li>
                <li>Popups, Click Unders, transitional page ads, layer ads, Adult, and Incentivized traffic are strictly prohibited.</li>
                <li>Traffic from non-approved countries will be void.</li>
                <li>Any advertising method that does not funnel to Advertiser's Site (e.g., wholesale and drop shipping) is strictly prohibited.</li>
                <li>Do not bid on or purchase keywords including the word "Temu" or any other trademark of Temu, its affiliates, or variations/misspellings thereof.</li>
                <li>Do not use or display Temu names/trademarks in offline material or email.</li>
                <li>Do not use Program Content in connection with any client-side software application (browser plug-in, toolbar, extension, etc.) except those approved by Advertiser.</li>
                <li>Do not intercept, record, redirect, read, or fill in the contents of any electronic form submitted to Advertiser.</li>
                <li>Do not use Doorway Pages to optimize rankings.</li>
                <li>Do not push emails or messages without Advertiser's prior consent. Do not use false or misleading promotional terms.</li>
                <li>Do not track repeat visits to Advertiser's Site without a purchase to serve retargeting ads.</li>
                <li>Forbidden traffic types include: brand-bidding, TM+, adult, paid search, spam e-mail, clickunder/popunder, doorways, incentive, spam SMS/Messenger, autoredirect, retargeting, pop-up.</li>
                <li>Do not cloak, hide, spoof, or obscure the URL of any Site containing a Qualifying Link or the user agent of any application displaying Program Content.</li>
                <li>Do not interfere with, manipulate, mislead, or deceive users into clicking a Qualifying Link.</li>
                <li>Do not use any advertisement that impersonates Advertiser, its Affiliates, or any official representatives.</li>
                <li>Do not post Qualifying Links alongside contextually irrelevant content, including fake promotions, entertainment news, or deceptive product reviews.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Publicity and Confidentiality</h2>
              <p>Media Partner shall not create, publish, distribute, or permit any public announcement related to these Terms without first receiving Advertiser's written approval.</p>
              <p className="mt-3">All information and materials made available by Advertiser that is not generally known to the public, including the terms of this Agreement, Advertiser's business and financial information, customer lists, pricing, and sales information ("Confidential Information"), shall remain the property of Advertiser. Media Partner will not disclose or use Confidential Information except as authorized in these Terms.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">10. Term and Termination</h2>
              <p>The term of this Agreement is continuous unless and until either party properly terminates it. Advertiser shall provide 7 days written notice via the Network Service. Advertiser may terminate immediately in the event Media Partner violates this Agreement.</p>
              <p className="mt-3">Upon termination: (i) Media Partner shall be entitled only to unpaid commissions earned prior to the termination date; (ii) all rights and licenses shall immediately terminate; (iii) Media Partner shall cease all uses of Advertiser's trademarks and remove all Advertiser links; (iv) Media Partner shall destroy or return all Confidential Information.</p>
              <p className="mt-3">Advertiser may, in its sole discretion, cancel, change, suspend, or modify any aspect of these Terms at any time, without notice.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">11. General Provisions</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Waiver:</strong> No forbearance or delay shall restrict either party's rights. No waiver operates as a waiver of any subsequent breach.</li>
                <li><strong>Assignment:</strong> Advertiser may assign any or all of its rights under this Agreement upon notification to Media Partner.</li>
                <li><strong>Audit Rights:</strong> Media Partner agrees to maintain books and records relating to compliance for the term of this Agreement and one (1) year thereafter.</li>
                <li><strong>Force Majeure:</strong> Neither party shall be liable for failure or delay caused by circumstances beyond reasonable control, including acts of God, war, fire, flood, or Internet failure.</li>
                <li><strong>Entire Agreement:</strong> This Agreement represents the entire understanding relating to its subject matter and supersedes any previous agreement.</li>
                <li><strong>Severability:</strong> If any provision is held illegal, invalid, or unenforceable, the remainder of the Agreement shall not be affected.</li>
                <li><strong>Relationship of Parties:</strong> The relationship is that of independent contractors. This Agreement does not create any association, partnership, joint venture, or agency relationship.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">12. Governing Law</h2>
              <p>This Agreement shall be governed by and construed in accordance with the substantive laws of Hong Kong, without regard to its choice of law provisions. Disputes shall first be resolved through good-faith negotiation, then mediation at the Hong Kong International Arbitration Centre (HKIAC), and finally, if unresolved, by arbitration administered by HKIAC.</p>
              <p className="mt-3">If the Media Partner is incorporated in the United States, United Kingdom, Singapore, or Hong Kong, Advertiser may elect by written notice to have a Dispute heard by courts of competent jurisdiction instead of arbitration.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">13. Anti-Bribery and Anti-Corruption</h2>
              <p>Media Partner and all associated persons must comply with all applicable anti-corruption laws, including the U.S. Foreign Corrupt Practices Act and the U.K. Bribery Act. Media Partner must not make or offer any improper payments, bribes, kickbacks, or benefits to any Advertiser-related party, government official, political party, or other person to obtain business advantage.</p>
              <p className="mt-3">Media Partner must cooperate with Advertiser's compliance audits and investigations. Any noncompliance may result in cancellation of bidding qualification, suspension or termination of this Agreement, withholding of outstanding invoices, and liquidated damages of 30% of total fees under all services.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Exhibit A – Endorsement Guidelines</h2>
              <p>In accordance with the FTC's Guides Concerning Endorsements and Testimonials, Media Partner must adhere to the following guidelines when publishing content about Temu products or services:</p>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li><strong>Disclose Connection:</strong> Clearly disclose your "material connections" with Advertiser, including any compensation, free products, gifts, or special access privileges, in close proximity to any statements about Temu.</li>
                <li><strong>Clear and Prominent Disclosure:</strong> The disclosure must not be buried in links, Terms and Conditions, or after a "more" button. On social media, use hashtags such as #sponsored, #paid, or #ad. Hashtags like #partner or #thanks alone are insufficient.</li>
                <li><strong>Platform-Specific Requirements:</strong>
                  <ul className="list-circle pl-6 space-y-1 mt-2">
                    <li>Instagram: Disclosure in the first two lines, above the "more" button.</li>
                    <li>Video/YouTube: Disclosure in the video itself at the beginning.</li>
                    <li>TikTok/Snapchat Stories: Superimpose disclosure over visuals clearly.</li>
                    <li>Blogs: Disclosure near the top, not buried at the bottom.</li>
                  </ul>
                </li>
                <li><strong>Honest Opinions:</strong> Statements must reflect honest and truthful opinions and actual experiences. Content must be in good taste and free of inappropriate language.</li>
                <li><strong>Truthful Factual Statements:</strong> Only make factual statements about Advertiser or products that you know to be true and can verify.</li>
                <li><strong>Intellectual Property:</strong> Never post content that violates the intellectual property rights of any third party. Do not alter or modify any logo, image, copyright, or trademark provided by Advertiser.</li>
                <li><strong>Confidentiality:</strong> Do not share confidential information that is not yet public without prior written approval from Advertiser.</li>
                <li><strong>No Inappropriate Association:</strong> Do not associate Temu or its products with any inappropriate or controversial content.</li>
              </ul>
              <p className="mt-3 font-medium">Advertiser reserves the right to monitor Media Partner's compliance with these guidelines and to terminate participation in the event of any noncompliance.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Additional Program Policies</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Search Campaigns:</strong> Media Partner will not bid on or purchase keywords, search terms, or other identifiers, including the word "Temu" or any other Temu trademark.</li>
                <li><strong>Use of Logos and Trademarks:</strong> Media Partner may use Advertiser's name/trademarks in the name of a software tool or application only with Advertiser's prior written approval.</li>
                <li><strong>Incentivized Traffic:</strong> Allowed only with Advertiser's prior written approval.</li>
                <li><strong>Email:</strong> Allowed only with Advertiser's prior written approval.</li>
                <li><strong>Software:</strong> Temu must be on an affirmative click basis for all software, extensions, and toolbars.</li>
                <li><strong>Sub-Affiliates:</strong> Only single-tier allowed. Publisher must seek approval for each sub-affiliate before extending Temu's offer. Approved sub-affiliates must have an individual identifier tied to their website. Publisher must provide sub-affiliate performance reporting.</li>
                <li><strong>Social Media:</strong> Requires written approval from Temu.</li>
                <li><strong>Coupons and Promotional Codes:</strong> Publishers may only use coupons and promotional codes provided exclusively through the affiliate program.</li>
                <li><strong>Add to Favorite:</strong> Do not run "Add to Favorite" pop-ups or campaigns that lead customers to believe they are bookmarking the official Temu site.</li>
                <li><strong>Banners/Links:</strong> Do not use Temu banners or links as pop-ups or pop-unders.</li>
                <li><strong>Voucher Codes:</strong> Temu reserves the right to cancel a voucher at any time. Any affiliate using a voucher code not directly supplied to them will have commissions declined.</li>
                <li><strong>Google Shopping:</strong> Publishers cannot use the product feed to advertise on Google Shopping.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Payment Restrictions</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>There will be no payment on online sales when the customer status is not new. A customer is not new if they have previously placed order(s) or if the device they used has previously placed order(s) with the Advertiser.</li>
                <li>Cancelled or refunded orders are not subject to any payment.</li>
                <li>Actions can be cancelled (chargebacks) if: an action is incomplete; a customer cancels or returns; an action is made fraudulently; an action is carried out outside the area serviced by the Advertiser; or the Advertiser is unable to ship goods.</li>
                <li>Advertiser may delay payment for investigation and may refuse payment for actions that are fraudulent, suspicious, or in violation of these Terms.</li>
              </ul>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
};

export default TemuTerms;
